program Regressi;


uses
  Forms,
  oneinst in 'oneinst.pas',
  constreg in 'constreg.pas',
  maths in 'maths.pas',
  regutil in 'regutil.pas',
  uniteker in 'uniteker.pas',
  fft in 'fft.pas',
  statcalc in 'statcalc.pas',
  systdiff in 'systdiff.pas',
  regmain in 'regmain.pas' {FRegressiMain},
  optcolordlg in 'optcolordlg.pas' {OptionCouleurDlg},
  optfft in 'optfft.pas' {OptionsFFTDlg},
  supprdlg in 'supprdlg.pas' {SuppressionDlg},
  lecttext in 'lecttext.pas' {LectureTexteDlg},
  optline in 'optline.pas' {OptionLigneDlg},
  zoomman in 'zoomman.pas' {ZoomManuelDlg},
  newvar in 'newvar.pas' {NewVarDlg},
  graphker in 'graphker.pas',
  statisti in 'statisti.pas' {Fstatistique},
  filerrr in 'filerrr.pas',
  curmodel in 'curmodel.pas' {CurseurModeleDlg},
  options in 'options.pas' {OptionsDlg},
  modelegr in 'modelegr.pas',
  choixtang in 'choixtang.pas' {ChoixTangenteDlg},
  graphpar in 'graphpar.pas' {fgrapheParam},
  graphvar in 'graphvar.pas' {FgrapheVariab},
  cursdata in 'cursdata.pas' {ReticuleDataDlg},
  pagecopy in 'pagecopy.pas' {PageCopyDlg},
  selpage in 'selpage.pas' {SelectPageDlg},
  pagecalc in 'pagecalc.pas' {PageCalcDlg},
  varkeyb in 'varkeyb.pas' {NewClavierDlg},
  regprint in 'regprint.pas' {PrintDlg},
  identPagesU in 'identPagesU.pas' {ChoixIdentPagesDlg},
  statopt in 'statopt.pas' {StatOptDlg},
  modif in 'modif.pas' {ModifDlg},
  valeurs in 'valeurs.pas' {FValeurs},
  choixmodeleGlb in 'choixmodeleGlb.pas' {ChoixModeleGlbDlg},
  choixparamanim in 'choixparamanim.pas' {AnimParamDlg},
  coordphys in 'coordphys.pas' {FcoordonneesPhys},
  affectenom in 'affectenom.pas' {AffecteNomDlg},
  saveparam in 'saveparam.pas' {SaveParamDlg},
  optionsvitesse in 'optionsvitesse.pas' {OptionsVitesseDlg},
  regdde in 'regdde.pas' {FormDDE},
  selparam in 'selparam.pas' {selParamDlg},
  origineu in 'origineu.pas' {OrigineDlg},
  choixmodele in 'choixmodele.pas' {ChoixModeleDlg},
  optModele in 'optModele.pas' {OptionModeleDlg},
  compile in 'compile.pas',
  addPageExp in 'addPageExp.pas' {AddPageExpDlg},
  ZoomManuelFFT in 'ZoomManuelFFT.pas' {ZoomManuelFFTdlg},
  indicateurU in 'indicateurU.pas' {indicateurDlg},
  saveHarm in 'saveHarm.pas' {SaveHarmoniqueDlg},
  constante in 'constante.pas' {ConstanteUnivDlg},
  savePosition in 'savePosition.pas' {SavePositionDlg},
  PropCourbe in 'PropCourbe.pas' {PropCourbeForm},
  about in 'about.pas' {AboutBox},
  graphfft in 'graphfft.pas' {FGrapheFFT},
  Latex in 'Latex.pas',
  latexreg in 'latexreg.pas' {LatexDlg},
  aidekey in 'aidekey.pas',
  OptionsAffModeleU in 'OptionsAffModeleU.pas' {OptionsAffModeleDlg},
  WavMain in 'Images\WavMain.pas' {WaveForm},
  TestInWav in 'Images\TestInWav.pas' {TestWavDlg},
  grapheu in 'Images\grapheu.pas',
  FusionU in 'FusionU.pas' {FusionDlg},
  ChronoBitmap in 'Images\ChronoBitmap.pas' {ChronoForm},
  ChronoEch in 'Images\ChronoEch.pas' {EchelleMecaBmpDlg},
  CourbesU in 'Images\CourbesU.pas' {CourbesForm},
  courbesEch in 'Images\courbesEch.pas' {EchelleBmpDlg},
  selColonne in 'selColonne.pas' {SelectColonneDlg},
  pageechant in 'pageechant.pas' {PageEchantillonDlg},
  interfMain in 'Images\interfMain.pas' {OptiqueForm},
  savemodele in 'savemodele.pas' {SaveModeleDlg},
  graph3D in 'graph3D.pas' {fgraphe3D},
  coord3D in 'coord3D.pas' {Fcoordonnees3D},
  ChronoU in 'Images\ChronoU.pas' {VideoChronoForm},
  pagedistrib in 'pagedistrib.pas' {PageDistribDlg},
  coordEuler in 'coordEuler.pas' {FcoordonneesEuler},
  graphEuler in 'graphEuler.pas' {FgrapheEuler},
  mathml_Presentation in 'mathml_Presentation.pas',
  loupeU in 'Images\loupeU.pas' {LoupeForm},
  hdf5dll in 'hdf5dll.pas',
  modeleNum in 'modeleNum.pas',
  RollingShutterU in 'Images\RollingShutterU.pas' {RollingShutterForm},
  RollingShutterCalc in 'Images\RollingShutterCalc.pas',
  Videoffmpeg in 'Images\Videoffmpeg.pas' {ffmpegForm},
  EphemerU in 'EphemerU.pas' {EphemerForm},
  filerw3U in 'filerw3U.pas',
  ArduinoCfg in 'arduino\ArduinoCfg.pas' {ArduinoDlg},
  ArduinoOscilloCfg in 'arduino\ArduinoOscilloCfg.pas' {ArduinoOscilloDlg},
  arduinoU in 'arduino\arduinoU.pas' {ArduinoForm},
  arduinoWifiDirect in 'arduino\arduinoWifiDirect.pas' {ArduinoWifiDirectForm},
  ArduinoWifiDirectCfg in 'arduino\ArduinoWifiDirectCfg.pas' {ArduinoWifiDirectDlg},
  arduinoGraphe in 'arduino\arduinoGraphe.pas',
  arduinoOscillo in 'arduino\arduinoOscillo.pas' {ArduinoOscilloForm},
  captureCamera in 'Images\captureCamera.pas' {VideoForm},
  unitGraphe in 'unitGraphe.pas' {unitGrapheDlg},
  arduinoNew in 'arduino\arduinoNew.pas' {ArduinoNewForm},
  ArduinoCfgNew in 'arduino\ArduinoCfgNew.pas' {ArduinoNewDlg},
  InterfCapture in 'Images\InterfCapture.pas' {InterfCaptureForm};

{$R *.RES}

begin
  Application.Title := 'Regressi';
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TFRegressiMain, FRegressiMain);
  Application.CreateForm(TOptionsDlg, OptionsDlg);
  Application.CreateForm(TFormDDE, FormDDE);
  Application.CreateForm(TChoixModeleDlg, ChoixModeleDlg);
  Application.CreateForm(TindicateurDlg, indicateurDlg);
  Application.CreateForm(TConstanteUnivDlg, ConstanteUnivDlg);
  Application.CreateForm(TFcoordonneesPhys, FcoordonneesPhys);
  Application.CreateForm(TInterfCaptureForm, InterfCaptureForm);
  Application.Run;
end.
